# Generated by Django 5.2 on 2025-06-16 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0001_initial'),
        ('products', '0002_rename_itemtypemodel_itemstyle'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bagitem',
            unique_together={('bag', 'product', 'size')},
        ),
    ]
