# Generated by Django 5.2 on 2026-06-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='homepage_image',
            field=models.ImageField(blank=True, upload_to='homepage_categories/'),
        ),
    ]
