# Generated by Django 5.2 on 2026-06-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgroup',
            name='materials_and_care',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='productgroup',
            name='size_and_fit',
            field=models.TextField(blank=True),
        ),
    ]
