# Generated by Django 5.2 on 2025-05-16 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemTypeModel',
            new_name='ItemStyle',
        ),
    ]
