# Generated by Django 5.2 on 2026-01-13 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='model_size',
        ),
    ]
