# Generated by Django 5.2 on 2025-05-12 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributevalue',
            name='applicable_categories',
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='parent',
        ),
    ]
