# Generated by Django 5.2 on 2025-06-26 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='fit',
        ),
    ]
