# Generated by Django 5.2 on 2026-06-09 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productgroup_materials_and_care_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productgroup',
            old_name='size_and_fit',
            new_name='sizing',
        ),
    ]
