# Generated by Django 5.2 on 2025-04-30 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_is_active_product_sale_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_model',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
