# Generated by Django 5.2 on 2025-04-30 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_tags_delete_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='color',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
