# Generated by Django 5.2 on 2025-04-30 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productimage_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='product_videos/'),
        ),
        migrations.DeleteModel(
            name='ProductVideo',
        ),
    ]
