# Generated by Django 5.2 on 2025-07-02 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_color_product_color_name_product_color_hex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='color_name',
            new_name='color',
        ),
    ]
