# Generated by Django 5.2 on 2026-06-14 12:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_size_and_fit_productgroup_sizing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['homepage_order', 'name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='featured_on_homepage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='homepage_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='category',
            name='homepage_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='homepage_categories/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='homepage_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
