# Generated by Django 5.2 on 2025-07-07 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_sizes_remove_product_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsizestock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_stocks', to='products.product'),
        ),
    ]
