# Generated by Django 5.2 on 2026-06-14 13:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_category_options_category_featured_on_homepage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['homepage_order', 'name'], 'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='featured_on_homepage',
        ),
        migrations.RemoveField(
            model_name='category',
            name='homepage_description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='homepage_image',
        ),
        migrations.RemoveField(
            model_name='category',
            name='homepage_order',
        ),
        migrations.AddField(
            model_name='activity',
            name='featured_on_homepage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='homepage_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='activity',
            name='homepage_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='homepage_categories/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='homepage_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
