# Generated by Django 5.2 on 2025-04-30 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_video_delete_productvideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='alt_text',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='color',
        ),
    ]
