# Generated by Django 5.2 on 2025-07-07 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productsizestock_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsizestock',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_stocks', to='products.size'),
        ),
    ]
