# Generated by Django 5.2 on 2025-04-30 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productvideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_model',
        ),
    ]
