# Generated by Django 5.2 on 2026-06-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_activity_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='homepage_description',
            field=models.TextField(blank=True),
        ),
    ]
