# Generated by Django 5.2 on 2025-07-10 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_tags_productgroup_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='model_size',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
