# Generated by Django 5.2 on 2026-06-22 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_activity_homepage_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='StylingRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='styling_recommendations', to='products.productgroup')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productgroup')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('source', 'target')},
            },
        ),
    ]
