# Generated by Django 5.2 on 2025-07-14 11:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_model_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='gender',
        ),
        migrations.AddField(
            model_name='productgroup',
            name='gender',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
