# Generated by Django 5.2 on 2026-06-22 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_stylingrecommendation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StylingRecommendation',
        ),
    ]
