# Generated by Django 5.2 on 2026-06-22 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_delete_stylingrecommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgroup',
            name='styling_recommendation',
            field=models.ManyToManyField(blank=True, related_name='recommended_by', to='products.productgroup'),
        ),
    ]
