# Generated by Django 5.2 on 2026-06-22 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_productgroup_styling_recommendation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productgroup',
            old_name='styling_recommendation',
            new_name='styling_recommendations',
        ),
    ]
