# Generated by Django 5.2 on 2026-06-23 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_productgroup_styling_recommendations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_primary_variant',
            field=models.BooleanField(default=False),
        ),
    ]
